server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: shixindonga123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:com/example/demo/mapper/*Mapper.xml


#showSql
#logging:
#  level:
#    com:
#      example:
#        demo:
#          mapper : debug

myconf:

  ip: http://localhost

mybatis-plus:
  #  global-config:
  #    db-config:
  #      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/demo/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity

